= Advent of code 2019
:doctype: book
:toc:

image:https://godoc.org/gitlab.com/jhinrichsen/adventofcode2019?status.svg["godoc", link="https://godoc.org/gitlab.com/jhinrichsen/adventofcode2019"]
image:https://goreportcard.com/badge/gitlab.com/jhinrichsen/adventofcode2019["Go report card", link="https://goreportcard.com/report/gitlab.com/jhinrichsen/adventofcode2019"]
image:https://gitlab.com/jhinrichsen/adventofcode2019/badges/master/pipeline.svg[link="https://gitlab.com/jhinrichsen/adventofcode2019/-/commits/master",title="pipeline status"]
image:https://gitlab.com/jhinrichsen/adventofcode2019/badges/master/coverage.svg[link="https://gitlab.com/jhinrichsen/adventofcode2019/-/jobs",title="coverage report"]

This is an implementation of https://adventofcode.com/2019[Advent of Code 2019] in Go.

== Build from source

----
$ go get gitlab.com/jhinrichsen/adventofcode2019
----

== Environment

=== 2019

- Go 1.24
- vim, vim-go, gopls, fed by an HHKB
- VisualStudio Code for debugging
- Linux (various distributions)
- Prompts: Claude Code

== Intel Performance

All benchmarks were executed on Intel(R) Xeon(R) CPU @ 2.60GHz architecture.
Performance characteristics may vary on different CPU architectures, particularly
on hybrid architectures with P-cores and E-cores.

== Overview

Number of tries for a correct answer:

|===
| Day | Part 1 | Part 2 | Title

| 1   |   1    |   1    | The Tyranny of the Rocket Equation
| 2   |   1    |   1    | 1202 Program Alarm
| 3   |   1    |   1    | Crossed Wires
| 4   |   1    |   1    | Secure Container
| 5   |   2    |   2    | Sunny with a Chance of Asteroids
| 6   |   1    |   1    | Universal Orbit Map
| 7   |   1    |   1    | Amplification Circuit
| 8   |   1    |   1    | Space Image Format
| 9   |   1    |   1    | Sensor Boost
| 10  |   1    |   1    | Monitoring Station
| 11  |   1    |   1    | Space Police
| 12  |   1    |   -    | The N-Body Problem
| 13  |   1    |   1    | Care Package
| 14  |   3    |   1    | Space Stoichiometry
| 15  |   1    |   1    | Oxygen System
| 16  |   1    |   1    | Flawed Frequency Transmission
| 17  |   1    |   1    | Set and Forget
| 18  |   2    |   1    | Many-Worlds Interpretation
| 19  |   1    |   4    | Tractor Beam
| 20  |   1    |   2    | Donut Maze
| 21  |   1    |   1    | Springdroid Adventure
| 22  |   -    |   -    | Slam Shuffle
| 23  |   -    |   -    | Category Six
| 24  |   -    |   -    | Planet of Discord
| 25  |   -    |   -    | Cryostasis

|===

== Day 19: Tractor Beam

Part 2 required multiple algorithmic iterations to find the correct approach:

**Failed approaches:**
- Attempt 1: Checking bottom-right corner instead of top-right
- Attempt 2: Checking both top-right and bottom-left from top-left corner
- Attempt 3: Optimization that incorrectly skipped beam points

**Successful approach:**
- Scan rows as the BOTTOM edge of the 100x100 square
- For each row y, find the leftmost beam point (bottom-left corner)
- Check if the top-right corner at (x+99, y-99) is also in the beam
- Return the top-left corner coordinates (x, y-99)

This approach works because the tractor beam expands monotonically, making a
row-by-row bottom-edge scan both correct and efficient.

== Benchmarks

Results from `make total` on Intel(R) Xeon(R) CPU @ 2.60GHz:

----
goos: linux
goarch: amd64
pkg: gitlab.com/jhinrichsen/adventofcode2019
cpu: Intel(R) Xeon(R) CPU @ 2.60GHz
BenchmarkDay10Part1-16    	     147	   8152138 ns/op	 4300319 B/op	     948 allocs/op
BenchmarkDay14Part1-16    	   14290	     82359 ns/op	   37223 B/op	     380 allocs/op
BenchmarkDay14Part2-16    	    1016	   1226413 ns/op	  173357 B/op	     683 allocs/op
BenchmarkDay15Part1-16    	      13	  82933484 ns/op	51392433 B/op	  105674 allocs/op
BenchmarkDay15Part2-16    	      12	 102327223 ns/op	57866777 B/op	  131108 allocs/op
BenchmarkDay16Part1-16    	      25	  43344598 ns/op	  542976 B/op	     101 allocs/op
BenchmarkDay16Part2-16    	      14	  77158597 ns/op	 4207872 B/op	       2 allocs/op
BenchmarkDay17Part1-16    	      68	  18194266 ns/op	43743159 B/op	    2233 allocs/op
BenchmarkDay17Part2-16    	      50	  22993333 ns/op	43946105 B/op	    2094 allocs/op
BenchmarkDay18Part1-16    	       1	7948274701 ns/op	1199136976 B/op	   40596 allocs/op
BenchmarkDay18Part2-16    	       2	 915211528 ns/op	40854496 B/op	   21810 allocs/op
BenchmarkDay19Part1-16    	       9	 112241838 ns/op	155502378 B/op	   48021 allocs/op
BenchmarkDay19Part2-16    	       1	23739617884 ns/op	37568474848 B/op	11796388 allocs/op
BenchmarkDay20Part1-16    	     492	   2564065 ns/op	  675760 B/op	    1106 allocs/op
BenchmarkDay20Part2-16    	       2	 746991336 ns/op	104088420 B/op	 1151789 allocs/op
BenchmarkDay21Part1-16    	    1154	    962476 ns/op	  942768 B/op	      55 allocs/op
BenchmarkDay21Part2-16    	      85	  13949738 ns/op	  943072 B/op	      55 allocs/op
PASS
ok  	gitlab.com/jhinrichsen/adventofcode2019	51.285s
----

*Benchmark results:*

- *Total solve time (sum of ns/op)*: 33.84 seconds
- *Benchmark framework runtime*: 51.285s (includes overhead and multiple iterations)
- *Benchmarks run*: 17 (Day10-21 Part1/Part2 where implemented)

Notable performance characteristics:

- *Day 19 Part 2*: Dominates at 23.74s (70% of total) with 37GB allocations due to extensive beam scanning
- *Day 18 Part 1*: Second at 7.95s (23% of total) with complex maze pathfinding
- *Day 18 Part 2*: Third at 0.92s with optimized 4-robot pathfinding
- *Day 20 Part 2*: 0.75s for recursive maze with portal levels
- *Day 16 Part 2*: 0.08s for FFT with offset optimization

Performance bottlenecks are primarily in geometric search (Day 19) and path-finding
algorithms (Days 15, 18, 20) due to large search spaces. The single slowest operation
(Day 19 Part 2) accounts for 70% of total runtime.
